"""Agregar capture_id a factura

Revision ID: b0f9502f47a3
Revises: e0b9bd4958b2
Create Date: 2025-10-29 19:04:31.763786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f9502f47a3'
down_revision = 'e0b9bd4958b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capture_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facturas', schema=None) as batch_op:
        batch_op.drop_column('capture_id')

    # ### end Alembic commands ###
